[platformio]
default_envs = xiao_esp32s3_radiolib

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = chain+
build_unflags =
    -std=gnu++11
monitor_filters =
    esp32_exception_decoder
    time

[env:xiao_esp32s3]
; Basis-Environment ohne RadioLib (scaffold-only LoRaWAN)
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3
    -D SMARTTAG_FW_VERSION=\"3.0.0\"

[env:xiao_esp32s3_radiolib]
; Produktions-Environment mit RadioLib (echter OTAA Join)
upload_port = COM3
monitor_port = COM3
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4
    jgromes/RadioLib @ ^7.6.0
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3
    -D SMARTTAG_FW_VERSION=\"3.0.0\"
    -D SMARTTAG_ENABLE_RADIOLIB=1
    -D RADIOLIB_DEBUG_BASIC=1
    -D RADIOLIB_DEBUG_PROTOCOL=1
    -D RADIOLIB_DEBUG_PORT=Serial
