; PlatformIO – SmartTag CubeCell HTCC-AB02A 433MHz UART Modem
; Board: HTCC-AB02A (ASR6502, SX1262, 433MHz)

; HTCC-AB02A = cubecell_node (ASR6502, Cortex-M0+)
; CubeCell_Board_Pro war FALSCH (HTCC-AB03, ASR6601, Cortex-M4)
[env:cubecell_node_COM5]
platform    = heltec-cubecell
board       = cubecell_node
framework   = arduino

upload_port  = COM5
monitor_port = COM5
monitor_speed = 115200

build_flags =
    -D REGION_EU433

[env:cubecell_node_COM9]
platform    = heltec-cubecell
board       = cubecell_node
framework   = arduino

upload_port  = COM9
monitor_port = COM9
monitor_speed = 115200

build_flags =
    -D REGION_EU433

[env:cubecell_node_COM8]
platform    = heltec-cubecell
board       = cubecell_node
framework   = arduino

upload_port  = COM8
monitor_port = COM8
monitor_speed = 115200

build_flags =
    -D REGION_EU433
